import { fileURLToPath } from "node:url";

/** Versioned SQL migrations generated by Drizzle Kit (`pnpm db:generate`). */
export const MIGRATIONS_FOLDER = fileURLToPath(new URL("../drizzle", import.meta.url));
